-- Inserir Requisitos ISO 9001:2015
INSERT INTO public.iso_requirements (standard, version, clause_number, clause_title, description, guidance_notes, evidence_examples) VALUES
('ISO_9001', '2015', '4.1', 'Entendendo a organização e seu contexto', 'A organização deve determinar questões externas e internas relevantes para seu propósito e direção estratégica.', 'Considerar fatores legais, tecnológicos, competitivos, de mercado, culturais, sociais e econômicos. Realizar análise SWOT ou PESTEL.', ARRAY['Análise SWOT documentada', 'Análise de mercado', 'Matriz de stakeholders', 'Atas de reuniões estratégicas']),
('ISO_9001', '2015', '4.2', 'Necessidades e expectativas de partes interessadas', 'Determinar as partes interessadas relevantes ao SGQ e seus requisitos.', 'Identificar clientes, fornecedores, colaboradores, reguladores, acionistas e suas necessidades.', ARRAY['Matriz de partes interessadas', 'Pesquisas de satisfação', 'Contratos com clientes', 'Requisitos legais mapeados']),
('ISO_9001', '2015', '4.3', 'Escopo do sistema de gestão da qualidade', 'Determinar os limites e aplicabilidade do SGQ.', 'Documentar processos incluídos, exclusões justificadas, produtos e serviços cobertos.', ARRAY['Documento de escopo do SGQ', 'Manual da qualidade', 'Mapa de processos']),
('ISO_9001', '2015', '4.4', 'Sistema de gestão da qualidade e seus processos', 'Estabelecer, implementar, manter e melhorar continuamente o SGQ.', 'Identificar processos, suas interações, critérios, recursos, riscos e oportunidades.', ARRAY['Mapa de processos', 'Procedimentos documentados', 'Indicadores de desempenho', 'Matriz de riscos']),
('ISO_9001', '2015', '5.1', 'Liderança e comprometimento', 'A alta direção deve demonstrar liderança e comprometimento com o SGQ.', 'Assegurar foco no cliente, estabelecer política e objetivos da qualidade, prover recursos.', ARRAY['Política da qualidade assinada', 'Atas de análise crítica', 'Planos de investimento', 'Comunicados da direção']),
('ISO_9001', '2015', '5.2', 'Política da qualidade', 'Estabelecer, implementar e manter uma política da qualidade.', 'Deve ser apropriada ao propósito, prover estrutura para objetivos, incluir compromisso com requisitos e melhoria contínua.', ARRAY['Política da qualidade documentada', 'Evidências de comunicação', 'Treinamentos sobre a política']),
('ISO_9001', '2015', '5.3', 'Papéis, responsabilidades e autoridades', 'Assegurar que responsabilidades e autoridades sejam atribuídas e comunicadas.', 'Definir organograma, descrições de cargos, matriz de responsabilidades (RACI).', ARRAY['Organograma', 'Descrições de cargos', 'Matriz RACI', 'Procurações e delegações']),
('ISO_9001', '2015', '6.1', 'Ações para abordar riscos e oportunidades', 'Determinar riscos e oportunidades que precisam ser abordados.', 'Realizar análise de riscos (FMEA, análise SWOT), definir ações preventivas.', ARRAY['Matriz de riscos', 'Análise FMEA', 'Planos de ação', 'Registros de oportunidades']),
('ISO_9001', '2015', '6.2', 'Objetivos da qualidade e planejamento', 'Estabelecer objetivos da qualidade mensuráveis.', 'Objetivos devem ser SMART (específicos, mensuráveis, alcançáveis, relevantes, temporais).', ARRAY['Objetivos documentados', 'Indicadores (KPIs)', 'Planos de ação', 'Relatórios de acompanhamento']),
('ISO_9001', '2015', '6.3', 'Planejamento de mudanças', 'Quando mudanças no SGQ forem necessárias, devem ser planejadas.', 'Considerar propósito, integridade do SGQ, disponibilidade de recursos, realocação de responsabilidades.', ARRAY['Planos de mudança', 'Análise de impacto', 'Comunicações de mudança', 'Registros de aprovação']);

-- Inserir Requisitos ISO 14001:2015
INSERT INTO public.iso_requirements (standard, version, clause_number, clause_title, description, guidance_notes, evidence_examples) VALUES
('ISO_14001', '2015', '4.1', 'Contexto da organização', 'Determinar questões externas e internas relevantes ao SGA.', 'Considerar condições ambientais, requisitos legais, expectativas de partes interessadas.', ARRAY['Análise de contexto ambiental', 'Legislação aplicável', 'Aspectos ambientais significativos']),
('ISO_14001', '2015', '4.2', 'Partes interessadas', 'Determinar partes interessadas e seus requisitos ambientais.', 'Identificar comunidades, ONGs, órgãos ambientais, clientes com requisitos ambientais.', ARRAY['Matriz de stakeholders', 'Requisitos de clientes', 'Licenças ambientais', 'Termos de compromisso']),
('ISO_14001', '2015', '4.3', 'Escopo do SGA', 'Determinar os limites e aplicabilidade do Sistema de Gestão Ambiental.', 'Definir instalações, atividades, produtos e serviços incluídos no SGA.', ARRAY['Documento de escopo', 'Limites geográficos', 'Atividades cobertas']),
('ISO_14001', '2015', '6.1.1', 'Ações para riscos e oportunidades', 'Determinar riscos e oportunidades relacionados a aspectos ambientais.', 'Identificar riscos de poluição, não conformidades legais, oportunidades de melhoria ambiental.', ARRAY['Matriz de riscos ambientais', 'Análise de perigos', 'Planos de contingência']),
('ISO_14001', '2015', '6.1.2', 'Aspectos ambientais', 'Identificar aspectos ambientais e determinar aqueles que são significativos.', 'Considerar emissões, descargas, resíduos, uso de recursos, numa perspectiva de ciclo de vida.', ARRAY['Levantamento de aspectos', 'Matriz de significância', 'Estudo de ciclo de vida']),
('ISO_14001', '2015', '6.1.3', 'Requisitos legais', 'Determinar e ter acesso aos requisitos legais aplicáveis.', 'Manter cadastro de legislação, avaliar conformidade periodicamente.', ARRAY['Cadastro de legislação', 'Avaliação de conformidade legal', 'Licenças e autorizações', 'Relatórios de conformidade']),
('ISO_14001', '2015', '6.1.4', 'Planejamento de ações', 'Planejar ações para abordar aspectos significativos e requisitos legais.', 'Definir objetivos, metas, programas ambientais, responsáveis e prazos.', ARRAY['Programas ambientais', 'Planos de ação', 'Cronogramas', 'Investimentos ambientais']),
('ISO_14001', '2015', '8.1', 'Planejamento e controle operacional', 'Estabelecer controles para atender requisitos do SGA.', 'Implementar procedimentos, instruções de trabalho, controles de engenharia.', ARRAY['Procedimentos operacionais', 'Instruções de trabalho', 'Planos de manutenção', 'Controles de processo']),
('ISO_14001', '2015', '8.2', 'Preparação e resposta a emergências', 'Estabelecer processos para preparação e resposta a emergências ambientais.', 'Identificar cenários de emergência (vazamentos, incêndios), treinar equipes.', ARRAY['Plano de emergência', 'Simulados', 'Registros de treinamento', 'Equipamentos de emergência']),
('ISO_14001', '2015', '9.1', 'Monitoramento e medição', 'Monitorar, medir, analisar e avaliar o desempenho ambiental.', 'Estabelecer indicadores, realizar monitoramento de emissões, efluentes, resíduos.', ARRAY['Programa de monitoramento', 'Relatórios analíticos', 'Calibração de equipamentos', 'Laudos laboratoriais']);

-- Inserir Requisitos ISO 45001:2018
INSERT INTO public.iso_requirements (standard, version, clause_number, clause_title, description, guidance_notes, evidence_examples) VALUES
('ISO_45001', '2018', '4.1', 'Contexto da organização', 'Determinar questões que afetam o sistema de gestão de SSO.', 'Considerar condições de trabalho, perigos existentes, cultura de segurança.', ARRAY['Análise de contexto de SSO', 'Histórico de acidentes', 'Cultura de segurança']),
('ISO_45001', '2018', '6.1.1', 'Ações para riscos', 'Determinar e avaliar riscos de SSO.', 'Identificar perigos, avaliar riscos, definir controles hierárquicos (eliminação, substituição, controles de engenharia, EPIs).', ARRAY['Matriz de riscos de SSO', 'APR - Análise Preliminar de Riscos', 'PGR - Programa de Gerenciamento de Riscos']),
('ISO_45001', '2018', '6.1.2', 'Identificação de perigos', 'Estabelecer processo de identificação contínua e proativa de perigos.', 'Considerar atividades rotineiras e não rotineiras, fatores humanos, infraestrutura.', ARRAY['Inventário de perigos', 'Inspeções de segurança', 'Relatos de quase-acidentes', 'Análise ergonômica']),
('ISO_45001', '2018', '6.1.3', 'Requisitos legais', 'Determinar requisitos legais de SSO aplicáveis.', 'Normas Regulamentadoras (NRs), legislação trabalhista, requisitos de seguradoras.', ARRAY['Cadastro de NRs', 'Licenças de funcionamento', 'PPP e LTCAT', 'Laudos técnicos']),
('ISO_45001', '2018', '6.2', 'Objetivos de SSO', 'Estabelecer objetivos de SSO mensuráveis.', 'Redução de acidentes, melhoria de indicadores (taxa de frequência, gravidade).', ARRAY['Objetivos de SSO', 'Indicadores de desempenho', 'Metas de redução', 'Programas de prevenção']),
('ISO_45001', '2018', '7.2', 'Competência', 'Assegurar competência de trabalhadores que afetam desempenho de SSO.', 'Treinamentos obrigatórios, reciclagens, capacitação em atividades críticas.', ARRAY['Matriz de treinamento', 'Certificados', 'Avaliação de competência', 'Treinamentos NRs']),
('ISO_45001', '2018', '7.4', 'Comunicação', 'Estabelecer processo de comunicação interna e externa de SSO.', 'CIPA, DDS (Diálogo Diário de Segurança), campanhas de conscientização.', ARRAY['Atas de CIPA', 'Registros de DDS', 'Campanhas de segurança', 'Comunicados de risco']),
('ISO_45001', '2018', '8.1', 'Planejamento e controle operacional', 'Eliminar perigos e reduzir riscos de SSO.', 'Implementar hierarquia de controles, procedimentos seguros de trabalho.', ARRAY['Procedimentos de trabalho seguro', 'Permissões de trabalho', 'APTs', 'Inspeções pré-operacionais']),
('ISO_45001', '2018', '8.2', 'Preparação para emergências', 'Estabelecer processos de resposta a emergências.', 'Brigada de emergência, simulados, rotas de fuga, primeiros socorros.', ARRAY['Plano de emergência', 'Simulados de evacuação', 'Treinamento de brigadistas', 'Equipamentos de emergência']),
('ISO_45001', '2018', '9.1', 'Monitoramento e medição', 'Monitorar e medir atividades relacionadas a SSO.', 'Indicadores reativos (acidentes) e proativos (inspeções, treinamentos).', ARRAY['Indicadores de SSO', 'CAT - Comunicação de Acidente', 'Inspeções de segurança', 'Monitoramento de saúde ocupacional']);

-- Inserir Requisitos ISO 39001:2012
INSERT INTO public.iso_requirements (standard, version, clause_number, clause_title, description, guidance_notes, evidence_examples) VALUES
('ISO_39001', '2012', '4.1', 'Contexto da organização', 'Entender o contexto de segurança viária da organização.', 'Considerar frota própria/terceirizada, rotas de risco, histórico de acidentes.', ARRAY['Análise de acidentes de trânsito', 'Mapeamento de rotas de risco', 'Perfil da frota']),
('ISO_39001', '2012', '4.2', 'Partes interessadas', 'Determinar partes interessadas em segurança viária.', 'Motoristas, passageiros, pedestres, autoridades de trânsito, seguradoras.', ARRAY['Stakeholders de SV', 'Requisitos de seguradoras', 'Acordos com transportadoras']),
('ISO_39001', '2012', '6.2', 'Objetivos de segurança viária', 'Estabelecer objetivos mensuráveis de SV.', 'Redução de acidentes, sinistros, violações, treinamento de motoristas.', ARRAY['Objetivos de SV', 'Indicadores de sinistralidade', 'Metas de redução', 'Programas de direção defensiva']),
('ISO_39001', '2012', '6.3', 'Fatores de desempenho', 'Identificar fatores que afetam desempenho de SV.', 'Exposição ao risco (km rodados), uso de equipamentos de segurança, fadiga.', ARRAY['Controle de quilometragem', 'Jornada de motoristas', 'Uso de cinto e dispositivos', 'Checklist veicular']),
('ISO_39001', '2012', '7.2', 'Competência de motoristas', 'Assegurar competência de motoristas e envolvidos no trânsito.', 'Treinamentos de direção defensiva, direção econômica, primeiros socorros.', ARRAY['CNH válida', 'Cursos de direção defensiva', 'Avaliação psicotécnica', 'Código de conduta']),
('ISO_39001', '2012', '8.1', 'Planejamento operacional', 'Implementar controles para gestão de segurança viária.', 'Manutenção preventiva, inspeções veiculares, tecnologia de rastreamento.', ARRAY['Plano de manutenção', 'Checklists veiculares', 'Sistema de rastreamento', 'Controle de pneus']),
('ISO_39001', '2012', '8.2', 'Preparação e resposta a emergências', 'Preparar respostas a incidentes de trânsito.', 'Primeiros socorros, acionamento de autoridades, apoio a vítimas.', ARRAY['Procedimento de emergência', 'Kits de primeiros socorros', 'Treinamento de condutores', 'Seguro de veículos']),
('ISO_39001', '2012', '9.1', 'Monitoramento de desempenho', 'Monitorar indicadores de segurança viária.', 'Acidentes, multas, velocidade média, comportamento de motoristas.', ARRAY['Relatórios de acidentes', 'Multas e infrações', 'Telemetria', 'Auditorias comportamentais']);

-- Mensagem de confirmação
SELECT 'Requisitos ISO inseridos com sucesso! Total: ' || COUNT(*) || ' requisitos' as resultado
FROM public.iso_requirements;