import { TourDefinition } from '@/types/tour';

export const tourDefinitions: Record<string, TourDefinition> = {
  'dashboard-intro': {
    id: 'dashboard-intro',
    title: 'Bem-vindo ao Dashboard',
    description: 'Conheça os principais recursos do seu dashboard',
    priority: 'user-initiated',
    steps: [
      {
        id: 'welcome',
        title: '👋 Bem-vindo!',
        description: 'Este tour rápido vai te mostrar como usar o dashboard de forma eficiente.',
        placement: 'center',
      },
      {
        id: 'sidebar',
        title: 'Navegação',
        description: 'Use a barra lateral para acessar todas as funcionalidades da plataforma.',
        target: '[data-tour="sidebar"]',
        placement: 'right',
        tip: 'Você pode minimizar a barra clicando no ícone de menu.',
      },
      {
        id: 'search',
        title: 'Busca Rápida',
        description: 'Use a busca para encontrar rapidamente qualquer informação. Pressione Ctrl+K para abrir.',
        target: '[data-tour="search"]',
        placement: 'bottom',
        tip: 'A busca inteligente aprende com suas preferências e mostra resultados relevantes primeiro.',
      },
      {
        id: 'metrics',
        title: 'Métricas Principais',
        description: 'Aqui você vê os indicadores mais importantes do seu negócio em tempo real.',
        target: '[data-tour="metrics"]',
        placement: 'bottom',
        tip: 'Clique em qualquer card para ver detalhes e histórico completo.',
      },
      {
        id: 'complete',
        title: '🎉 Parabéns!',
        description: 'Você concluiu o tour básico. Explore os outros tours para conhecer funcionalidades específicas.',
        placement: 'center',
      },
    ],
  },
  
  'license-management': {
    id: 'license-management',
    title: 'Gestão de Licenças',
    description: 'Aprenda a gerenciar licenças e certificações',
    priority: 'contextual',
    steps: [
      {
        id: 'intro',
        title: '📋 Gestão de Licenças',
        description: 'Mantenha todas as suas licenças e certificações organizadas e atualizadas.',
        placement: 'center',
      },
      {
        id: 'add-license',
        title: 'Adicionar Licença',
        description: 'Clique aqui para adicionar uma nova licença ou certificação.',
        target: '[data-tour="add-license"]',
        placement: 'left',
        allowInteraction: true,
        tip: 'Você pode importar várias licenças de uma vez usando planilhas Excel.',
      },
      {
        id: 'license-list',
        title: 'Lista de Licenças',
        description: 'Veja todas as suas licenças organizadas. Use filtros para encontrar rapidamente.',
        target: '[data-tour="license-list"]',
        placement: 'top',
      },
      {
        id: 'alerts',
        title: 'Alertas Automáticos',
        description: 'Configure alertas para ser notificado antes do vencimento das licenças.',
        target: '[data-tour="license-alerts"]',
        placement: 'bottom',
        tip: 'Alertas podem ser enviados por email, SMS ou notificação na plataforma.',
      },
      {
        id: 'history',
        title: 'Histórico de Ações',
        description: 'Acompanhe todas as alterações feitas nas licenças para auditoria e compliance.',
        target: '[data-tour="license-history"]',
        placement: 'top',
      },
    ],
  },

  'stakeholder-management': {
    id: 'stakeholder-management',
    title: 'Gestão de Stakeholders',
    description: 'Gerencie relacionamentos com partes interessadas',
    priority: 'contextual',
    steps: [
      {
        id: 'intro',
        title: '🤝 Stakeholders',
        description: 'Mantenha um registro organizado de todas as partes interessadas do projeto.',
        placement: 'center',
      },
      {
        id: 'add-stakeholder',
        title: 'Adicionar Stakeholder',
        description: 'Cadastre novos stakeholders com informações detalhadas de contato e relacionamento.',
        target: '[data-tour="add-stakeholder"]',
        placement: 'left',
        allowInteraction: true,
      },
      {
        id: 'categories',
        title: 'Categorias',
        description: 'Organize stakeholders por categorias como parceiros, fornecedores, clientes, órgãos reguladores, etc.',
        target: '[data-tour="stakeholder-categories"]',
        placement: 'right',
        tip: 'Você pode criar categorias personalizadas de acordo com sua necessidade.',
      },
      {
        id: 'engagement',
        title: 'Nível de Engajamento',
        description: 'Avalie e monitore o nível de engajamento de cada stakeholder com indicadores visuais.',
        target: '[data-tour="engagement-level"]',
        placement: 'bottom',
      },
      {
        id: 'matrix',
        title: 'Matriz de Influência',
        description: 'Visualize a matriz de poder e interesse para priorizar relacionamentos estratégicos.',
        target: '[data-tour="influence-matrix"]',
        placement: 'top',
        tip: 'A matriz ajuda a identificar stakeholders críticos que precisam de mais atenção.',
      },
    ],
  },

  'performance-module': {
    id: 'performance-module',
    title: 'Módulo de Performance',
    description: 'Monitore e melhore a performance da empresa',
    priority: 'contextual',
    requiredModules: ['performance'],
    steps: [
      {
        id: 'intro',
        title: '📊 Performance',
        description: 'Acompanhe KPIs e métricas de desempenho em tempo real.',
        placement: 'center',
      },
      {
        id: 'kpis',
        title: 'Indicadores (KPIs)',
        description: 'Defina e monitore os indicadores mais importantes para seu negócio.',
        target: '[data-tour="kpis"]',
        placement: 'bottom',
        tip: 'KPIs podem ser customizados de acordo com seus objetivos estratégicos.',
      },
      {
        id: 'goals',
        title: 'Metas e Objetivos',
        description: 'Configure metas e acompanhe o progresso da equipe com dashboards visuais.',
        target: '[data-tour="goals"]',
        placement: 'bottom',
      },
      {
        id: 'reports',
        title: 'Relatórios',
        description: 'Gere relatórios automáticos de performance para análise e tomada de decisão.',
        target: '[data-tour="performance-reports"]',
        placement: 'left',
        tip: 'Relatórios podem ser agendados para envio automático por email.',
      },
    ],
  },

  'quality-module': {
    id: 'quality-module',
    title: 'Módulo de Qualidade',
    description: 'Gestão de qualidade e não conformidades',
    priority: 'contextual',
    requiredModules: ['quality'],
    steps: [
      {
        id: 'intro',
        title: '✨ Qualidade',
        description: 'Gerencie processos de qualidade e controle de não conformidades.',
        placement: 'center',
      },
      {
        id: 'nonconformities',
        title: 'Não Conformidades',
        description: 'Registre e acompanhe não conformidades até a resolução com ações corretivas.',
        target: '[data-tour="nonconformities"]',
        placement: 'bottom',
        tip: 'Cada não conformidade pode ter múltiplas ações corretivas associadas.',
      },
      {
        id: 'audits',
        title: 'Auditorias',
        description: 'Planeje e execute auditorias de qualidade com checklists personalizados.',
        target: '[data-tour="audits"]',
        placement: 'bottom',
      },
      {
        id: 'processes',
        title: 'Processos',
        description: 'Mapeie e documente processos organizacionais para garantir padronização.',
        target: '[data-tour="quality-processes"]',
        placement: 'top',
        tip: 'Processos podem ser visualizados em fluxogramas interativos.',
      },
    ],
  },

  'esg-module': {
    id: 'esg-module',
    title: 'Módulo ESG',
    description: 'Gestão completa de ESG (Ambiental, Social e Governança)',
    priority: 'contextual',
    requiredModules: ['esg'],
    steps: [
      {
        id: 'intro',
        title: '🌱 ESG',
        description: 'Gerencie todas as iniciativas ESG da sua organização em um só lugar.',
        placement: 'center',
      },
      {
        id: 'emissions',
        title: 'Inventário de Emissões',
        description: 'Calcule e monitore emissões de gases de efeito estufa (GEE) pelos escopos 1, 2 e 3.',
        target: '[data-tour="emissions"]',
        placement: 'bottom',
        tip: 'Use fatores de emissão atualizados automaticamente de bases internacionais.',
      },
      {
        id: 'materiality',
        title: 'Análise de Materialidade',
        description: 'Identifique e priorize temas ESG relevantes para seus stakeholders.',
        target: '[data-tour="materiality"]',
        placement: 'left',
      },
      {
        id: 'reports',
        title: 'Relatórios ESG',
        description: 'Gere relatórios de sustentabilidade alinhados com GRI, SASB, TCFD e outros frameworks.',
        target: '[data-tour="esg-reports"]',
        placement: 'top',
        tip: 'Relatórios podem ser exportados em múltiplos formatos (PDF, Excel, Web).',
      },
    ],
  },
};
