import { TourDefinition } from '@/types/tour';

export const tourDefinitions: Record<string, TourDefinition> = {
  'dashboard-intro': {
    id: 'dashboard-intro',
    title: 'Bem-vindo ao Dashboard',
    description: 'Conheça os principais recursos do seu dashboard',
    priority: 'user-initiated',
    steps: [
      {
        id: 'welcome',
        title: '👋 Bem-vindo ao Daton!',
        description: 'Este tour rápido vai te mostrar como usar o dashboard de forma eficiente. Você pode pular qualquer etapa pressionando ESC.',
        placement: 'center',
      },
      {
        id: 'sidebar',
        title: '📋 Navegação Principal',
        description: 'Use a barra lateral para acessar todas as funcionalidades: ESG, Qualidade, RH, e muito mais.',
        target: '[data-tour="sidebar"]',
        placement: 'right',
        tip: 'Dica: Você pode minimizar a barra lateral clicando no ícone de menu para ter mais espaço na tela.',
      },
      {
        id: 'search',
        title: '🔍 Busca Inteligente',
        description: 'Encontre rapidamente qualquer página, documento ou informação. Pressione Ctrl+K (ou Cmd+K no Mac) para abrir a busca instantaneamente.',
        target: '[data-tour="search"]',
        placement: 'bottom',
        tip: 'A busca aprende com suas preferências e mostra os resultados mais relevantes primeiro. Use palavras-chave como "licença", "emissões", ou "relatório".',
      },
      {
        id: 'metrics',
        title: '📊 Indicadores em Tempo Real',
        description: 'Monitore os principais indicadores do seu negócio: emissões de CO₂, conformidade, número de colaboradores e certificações.',
        target: '[data-tour="metrics"]',
        placement: 'bottom',
        tip: 'Clique em qualquer card para ver detalhes completos, histórico e tendências. Os valores são atualizados automaticamente.',
      },
      {
        id: 'complete',
        title: '🎉 Tour Concluído!',
        description: 'Agora você conhece o básico. Explore os tours específicos de cada módulo (Licenças, ESG, Qualidade) para aprender recursos avançados.',
        placement: 'center',
      },
    ],
  },
  
  'license-management': {
    id: 'license-management',
    title: 'Gestão de Licenças e Certificações',
    description: 'Aprenda a gerenciar licenças, certificações e documentos regulatórios',
    priority: 'contextual',
    steps: [
      {
        id: 'intro',
        title: '📋 Central de Licenças',
        description: 'Mantenha todas as suas licenças ambientais, sanitárias, certificações ISO e documentos regulatórios organizados em um só lugar.',
        placement: 'center',
      },
      {
        id: 'add-license',
        title: '➕ Adicionar Licença',
        description: 'Cadastre novas licenças com todos os detalhes: número, órgão emissor, validade, condicionantes e documentos anexos.',
        target: '[data-tour="add-license"]',
        placement: 'left',
        allowInteraction: true,
        tip: 'Você pode importar múltiplas licenças de uma vez usando planilhas Excel. O sistema extrai dados automaticamente de PDFs usando IA.',
      },
      {
        id: 'license-list',
        title: '📑 Lista de Licenças',
        description: 'Visualize todas as suas licenças com status de validade. Use filtros para encontrar rapidamente por tipo, órgão ou status.',
        target: '[data-tour="license-list"]',
        placement: 'top',
      },
      {
        id: 'alerts',
        title: '🔔 Sistema de Alertas',
        description: 'Configure alertas automáticos para ser notificado antes do vencimento, renovações pendentes ou condicionantes não cumpridas.',
        target: '[data-tour="license-alerts"]',
        placement: 'bottom',
        tip: 'Alertas podem ser enviados por email, SMS ou notificação push. Configure diferentes períodos de antecedência (30, 60, 90 dias).',
      },
      {
        id: 'history',
        title: '📜 Rastreabilidade Total',
        description: 'Acompanhe o histórico completo: quem criou, editou, renovou ou anexou documentos. Essencial para auditorias e compliance.',
        target: '[data-tour="license-history"]',
        placement: 'top',
        tip: 'Todo histórico é imutável e exportável para relatórios de auditoria.',
      },
    ],
  },

  'stakeholder-management': {
    id: 'stakeholder-management',
    title: 'Gestão de Stakeholders',
    description: 'Mapeie e engaje com todas as partes interessadas',
    priority: 'contextual',
    steps: [
      {
        id: 'intro',
        title: '🤝 Mapeamento de Stakeholders',
        description: 'Identifique, organize e engaje com todas as partes interessadas: clientes, fornecedores, comunidades, órgãos reguladores, investidores e mais.',
        placement: 'center',
      },
      {
        id: 'add-stakeholder',
        title: '👥 Cadastrar Stakeholder',
        description: 'Registre informações completas: dados de contato, categoria, nível de influência, expectativas e histórico de interações.',
        target: '[data-tour="add-stakeholder"]',
        placement: 'left',
        allowInteraction: true,
        tip: 'Importe stakeholders em massa via Excel ou integre com seu CRM.',
      },
      {
        id: 'categories',
        title: '🏷️ Categorização',
        description: 'Organize por categorias: Parceiros, Fornecedores, Clientes, Comunidade Local, Órgãos Reguladores, Investidores, ONGs.',
        target: '[data-tour="stakeholder-categories"]',
        placement: 'right',
        tip: 'Crie categorias personalizadas de acordo com sua estratégia de stakeholder engagement.',
      },
      {
        id: 'engagement',
        title: '📈 Nível de Engajamento',
        description: 'Monitore o nível de engajamento em 5 níveis: Desconhecedor, Resistente, Neutro, Apoiador, Líder.',
        target: '[data-tour="engagement-level"]',
        placement: 'bottom',
        tip: 'Use indicadores visuais para identificar rapidamente stakeholders que precisam de mais atenção.',
      },
      {
        id: 'matrix',
        title: '🎯 Matriz de Poder/Interesse',
        description: 'Visualize a matriz de poder vs interesse para priorizar esforços de engajamento e comunicação estratégica.',
        target: '[data-tour="influence-matrix"]',
        placement: 'top',
        tip: 'Stakeholders com alto poder e alto interesse devem ser gerenciados de perto (quadrante "Gerenciar Proximamente").',
      },
    ],
  },

  'performance-module': {
    id: 'performance-module',
    title: 'Análise de Performance ESG',
    description: 'Monitore KPIs e analise tendências de desempenho',
    priority: 'contextual',
    requiredModules: ['performance'],
    steps: [
      {
        id: 'intro',
        title: '📊 Analytics Avançado',
        description: 'Construa análises personalizadas de emissões, resíduos, água, energia e outros indicadores ESG com visualizações interativas.',
        placement: 'center',
      },
      {
        id: 'kpis',
        title: '📉 Seleção de Métricas',
        description: 'Escolha entre diversos indicadores: Emissões de GEE, Consumo de Água, Geração de Resíduos, Energia, e mais.',
        target: '[data-tour="kpis"]',
        placement: 'bottom',
        tip: 'Combine múltiplas métricas em um único dashboard para análise comparativa.',
      },
      {
        id: 'comparison',
        title: '🔄 Análise Comparativa',
        description: 'Compare dados por períodos, ativos, escopos ou categorias. Identifique tendências e outliers rapidamente.',
        target: '[data-tour="comparison"]',
        placement: 'left',
      },
      {
        id: 'reports',
        title: '📄 Relatórios Exportáveis',
        description: 'Gere relatórios em PDF, Excel ou PowerPoint. Agende envios automáticos por email para stakeholders.',
        target: '[data-tour="performance-reports"]',
        placement: 'left',
        tip: 'Salve configurações de análise como templates para reutilizar mensalmente.',
      },
    ],
  },

  'esg-module': {
    id: 'esg-module',
    title: 'Gestão ESG Completa',
    description: 'Gerencie Ambiental, Social e Governança de forma integrada',
    priority: 'contextual',
    requiredModules: ['esg'],
    steps: [
      {
        id: 'intro',
        title: '🌱 Central ESG',
        description: 'Gerencie todos os pilares ESG (Ambiental, Social, Governança) com frameworks internacionais: GRI, SASB, TCFD, CDP.',
        placement: 'center',
      },
      {
        id: 'emissions',
        title: '🌍 Inventário de Emissões GEE',
        description: 'Calcule emissões Escopo 1, 2 e 3 usando metodologia GHG Protocol. Fatores de emissão atualizados automaticamente.',
        target: '[data-tour="emissions"]',
        placement: 'bottom',
        tip: 'Conecte com fornecedores para coletar dados de Escopo 3 automaticamente.',
      },
      {
        id: 'materiality',
        title: '🎯 Análise de Materialidade',
        description: 'Identifique temas ESG relevantes através de matriz de materialidade com engajamento de stakeholders.',
        target: '[data-tour="materiality"]',
        placement: 'left',
        tip: 'Realize consultas periódicas com stakeholders para manter a matriz atualizada.',
      },
      {
        id: 'targets',
        title: '🎯 Metas e Compromissos',
        description: 'Defina metas de redução de emissões, consumo de água, resíduos e outros indicadores. Acompanhe progresso em tempo real.',
        target: '[data-tour="targets"]',
        placement: 'bottom',
      },
      {
        id: 'reports',
        title: '📊 Relatórios de Sustentabilidade',
        description: 'Gere relatórios completos alinhados com GRI, SASB, TCFD. Exporte para PDF, HTML ou publicação web.',
        target: '[data-tour="esg-reports"]',
        placement: 'top',
        tip: 'Use templates pré-configurados ou crie relatórios personalizados com sua marca.',
      },
    ],
  },
};
